# Generated by Django 4.2.16 on 2024-12-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
