# Generated by Django 4.2.16 on 2024-12-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
