# Generated by Django 4.2.16 on 2024-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("tutors", "Tutors"),
                    ("learners", "Learners"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
