# Generated by Django 4.2.16 on 2024-12-26 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_alter_livesession_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="submission_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
